version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    # ensure Python dependencies are installed at container startup
    command: bash -lc "pip install --no-cache-dir -r requirements.txt && bash"